services:

    sync_user_magellan:
        class: Leoo\UserBundle\Services\Magellan\SyncUser
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: leoo.userbundle.updated }